on:
  issues:
    types: [opened]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Parse Body
      uses: rishabhgupta/split-by@v1
      id: split
      with:
        string: ${{ github.event.issue.body }}
        split-by: '\n\n'

    - name: Get Data
      env:
        TESTSPLIT: ${{ steps.split.output._1 }}
        ACTOR: ${{ github.event.issue.user.login }}
        NUMBER: ${{ github.event.issue.number }}
        # BODY: ${{ github.event.issue.body }}
        TITLE: ${{ github.event.issue.title }}
        # JSON: ${{ toJson(github.event) }}
      run: |
        echo $ACTOR a generado un nuevo issue $NUMBER
        echo "Detalles"
        echo Titulo: $TITLE
        echo $TESTSPLIT
      