on:
  issues:
    types: [opened]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Get Data
      env:
        ACTOR: ${{ github.event.issue.user.login }}
        NUMBER: ${{ github.event.issue.number }}
        BODY: ${{ github.event.issue.body }}
        TITLE: ${{ github.event.issue.title }}
      run: |
        echo $ACTOR a generado un nuevo issue #$NUMBER
        echo "Detalles"
        echo Titulo: $TITLE
        echo Descripcion: $BODY
      