on:
  issues:
    types: [opened]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Get Data
      run: echo A comment on issue $NUMBER
      env:
        Number: "Test"