name: Run on Merge to Development or Manually on PR to Development

on:
  pull_request:
    types:
      - closed  # Detecta cuando un PR se mergea
    branches:
      - master  # Solo PRs que se mergean a development

  workflow_dispatch:  # Permite ejecución manual

  jobs:
  run-on-dev:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' && github.event.pull_request.base.ref == 'development' ||
      github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom script
        run: echo "This runs only when a PR is merged to development or manually on a PR targeting development!"

