on:
  issues:
    types: [opened]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Get Data
      env:
        Number: ${{ toJson(github) }}
      run: |
        echo A comment on issue $NUMBER