name: Run on Merge to Development or Manually on PR to Development

on:
  pull_request:
    types:
      - closed  # Detecta cuando un PR se mergea
    branches:
      - master  # Solo PRs que se mergean a development

  workflow_dispatch:  # Permite ejecución manual

jobs:
  run-on-dev:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom script
        run: echo "This runs only when a PR is merged to development or manually on a PR targeting development {{ github.event.pull_request.base.ref }}"

