on:
  issues:
    types: [opened]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Parse Body
      uses: rishabhgupta/split-by@v1
      id: split
      with:
        string: "Test\n\nBody"
        split-by: '\n\n'

    - name: Get Data
      env:
        TEST0:  ${{ steps.split.outputs._0 }}
        TEST1:  ${{ steps.split.outputs._1 }}
        ACTOR: ${{ github.event.issue.user.login }}
        NUMBER: ${{ github.event.issue.number }}
        # BODY: ${{ github.event.issue.body }}
        TITLE: ${{ github.event.issue.title }}
        # JSON: ${{ toJson(github.event) }}
      run: |
        echo $TEST0
        echo $TEST1
        echo ${{ steps.split.outputs }}

      