name: Run on Merge to Development or Manually on PR to Development

on:
  pull_request:
    types:
      - closed  # Detecta cuando un PR se mergea
    branches:
      - master  # Solo PRs que se mergean a development

  workflow_dispatch:  # Permite ejecución manual

jobs:
  check-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Definir variable inicial
        run: echo "EXECUTION_TYPE=automatic" >> $GITHUB_ENV

      - name: Modificar variable si la ejecución es manual
        if: github.event_name == 'workflow_dispatch'
        run: echo "EXECUTION_TYPE=manual" >> $GITHUB_ENV

      - name: Mostrar valor final de la variable
        run: echo "Tipo de ejecución $EXECUTION_TYPE"

