on:
  issues:
    types: [opened]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Get Data
      id: build-image
      env:
        Number: ${{ github.event.issue.number }}
      run: |
        echo A comment on issue $NUMBER