on:
  workflow_dispatch:

name: Deploy Production QA Copec Helm Chart

env:
 Workflow: "Hola"
 
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Say Hello Mona it's Monday"
      run: echo "Today is $Workflow"

    
