on:
  workflow_dispatch:

name: Deploy Production QA Copec Helm Chart

env:
 Workflow: "Hola"
 
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: uno
      run: echo "Today is $Workflow"
    - name: dos
      if: ${{ env.Workflow == 'Hola' }}
      run: |
        echo "Workflow=Chao" >> "$GITHUB_OUTPUT"
    - name: tres
      run: echo "Today is $Workflow"

    
