on:
  issues:
    types: [opened]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Get Data
      run: echo $ACTOR a generado un nuevo issue  $NUMBER
      env:
        ACTOR: ${{ github.actor }}
        NUMBER: ${{ github.event.issue.number }}