on:
  issues:
    types: [opened]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Parse Body
      uses: JungWinter/split@v2.1.0
      id: split
      with:
        msg: "Test\nBody"
        separator: "\n"

    - name: Get Data
      env:
        TEST0:  ${{ steps.split.outputs._0 }}
        TEST1:  ${{ steps.split.outputs._1 }}
        ACTOR: ${{ github.event.issue.user.login }}
        NUMBER: ${{ github.event.issue.number }}
        # BODY: ${{ github.event.issue.body }}
        TITLE: ${{ github.event.issue.title }}
        # JSON: ${{ toJson(github.event) }}
        SPLIT: ${{ toJson(steps.split.outputs) }}
      run: |
        echo $TEST0
        echo $TEST1

      